#!/bin/bash

# name of the master
MASTER_NAME=${MASTER_NAME:-master}
NODE_NAME=${NODE_NAME:-node}

TAG_PREFIX=${TAG_PREFIX:-k8s}

API_ENDPOINT=${API_ENDPOINT:-https://api.digitalocean.com/}
DOCTL_FLAGS="-u ${API_ENDPOINT}"
DOCTL="doctl ${DOCTL_FLAGS}"

echo "- Destroying the droplets"
# delete the droplets
NODES=()
for TAG in "${TAG_PREFIX}"-master "${TAG_PREFIX}"-node; do
    DROPLET="$(${DOCTL} compute droplet list --format=ID --tag-name=${TAG} --no-header)"
    if [ "${DROPLET}" ]; then
        NODES+=("${DROPLET}")
    fi
done
if [ ${#NODES[@]} -gt 0 ]; then
    ${DOCTL} compute droplet delete -f ${NODES[@]}
fi

echo "- Destroying the tags"
# delete the tags
${DOCTL} compute tag delete -f "${TAG_PREFIX}"-master
${DOCTL} compute tag delete -f "${TAG_PREFIX}"-node

echo "- Destroying the node firewall"
FW_ID=$(${DOCTL} compute firewall list --format ID,Name --no-header | grep "${TAG_PREFIX}"-nodes | cut -d' ' -f1)
if [ -n "${FW_ID}" ]; then
    ${DOCTL} compute firewall delete "${FW_ID}" -f
fi

echo "- Destroying the master firewall"
FW_ID=$(${DOCTL} compute firewall list --format ID,Name --no-header | grep "${TAG_PREFIX}"-master | cut -d' ' -f1)
if [ -n "${FW_ID}" ]; then
    ${DOCTL} compute firewall delete "${FW_ID}" -f
fi

echo "- Destroy completed (took $SECONDS seconds)"
