#!/bin/bash

TAG_PREFIX=${TAG_PREFIX:-k8s}

if [ ! -f ~/.ssh/k8s/id_rsa ]; then
    SSH_ID=$(doctl -u "${API_ENDPOINT}" compute ssh-key list | grep "k8s-ssh" | cut -d' ' -f1)
    if [ -n "${SSH_ID}" ]; then
        SSH_KEY=$(doctl -u "${API_ENDPOINT}" compute ssh-key get "${SSH_ID}" --format FingerPrint --no-header)
    fi
    if [ -n "${SSH_KEY}" ]; then
        doctl -u "${API_ENDPOINT}" compute ssh-key delete "${SSH_KEY}" -f
    fi
fi

# name of the master
MASTER_NAME=${MASTER_NAME:-master}
NODE_NAME=${NODE_NAME:-node}

API_ENDPOINT=${API_ENDPOINT:-https://api.digitalocean.com/}

echo "- Destroying the droplets"
# delete the droplets
NODES=()
for TAG in "${TAG_PREFIX}"-master "${TAG_PREFIX}"-node; do
    DROPLET="$(doctl -u "${API_ENDPOINT}" compute droplet list --format=ID --tag-name=${TAG} --no-header)"
    if [ "${DROPLET}" ]; then
        NODES+=("${DROPLET}")
    fi
done
if [ ${#NODES[@]} -gt 0 ]; then
    doctl -u "${API_ENDPOINT}" compute droplet delete -f ${NODES[@]}
fi

echo "- Destroying the tags"
# delete the tags
doctl -u "${API_ENDPOINT}" compute tag delete -f "${TAG_PREFIX}"-master
doctl -u "${API_ENDPOINT}" compute tag delete -f "${TAG_PREFIX}"-node

echo "- Destroying the node firewall"
FW_ID=$(doctl -u "${API_ENDPOINT}" compute firewall list | grep "${TAG_PREFIX}"-nodes | cut -d' ' -f1)
if [ -n "${FW_ID}" ]; then
    doctl -u "${API_ENDPOINT}" compute firewall delete "${FW_ID}" -f
fi

echo "- Destroying the master firewall"
FW_ID=$(doctl -u "${API_ENDPOINT}" compute firewall list | grep "${TAG_PREFIX}"-master | cut -d' ' -f1)
if [ -n "${FW_ID}" ]; then
    doctl -u "${API_ENDPOINT}" compute firewall delete "${FW_ID}" -f
fi

echo "- Destroy completed"
