#!/bin/bash

if [ ! -f ~/.ssh/k8s/id_rsa ]; then
    SSH_ID=$(doctl compute ssh-key list | grep "k8s-ssh" | cut -d' ' -f1)
    if [ -n "${SSH_ID}" ]; then
        SSH_KEY=$(doctl compute ssh-key get "${SSH_ID}" --format FingerPrint --no-header)
    fi
    if [ -n "${SSH_KEY}" ]; then
        doctl compute ssh-key delete "${SSH_KEY}" -f
    fi
fi

# name of the master
MASTER_NAME=${MASTER_NAME:-master}
NODE_NAME=${NODE_NAME:-node}

NODE_COUNT=${NODE_COUNT:-3}

echo "- Destroying the droplets"
# delete the droplets
MASTER_ID=$(doctl compute droplet list | grep "${MASTER_NAME}" |cut -d' ' -f1)
if [ -n "${MASTER_ID}" ]; then
    doctl compute droplet delete -f "${MASTER_ID}"
fi

for i in $(seq "${NODE_COUNT}"); do
    NODE_ID=$(doctl compute droplet list | grep "${NODE_NAME}""$i" |cut -d' ' -f1)
    if [ -n "${NODE_ID}" ]; then
        doctl compute droplet delete -f "${NODE_ID}"
    fi
done

echo "- Destroying the tags"
# delete the tags
doctl compute tag delete -f k8s-master
doctl compute tag delete -f k8s-node

echo "- Destroying the load balancer"
LB_ID=$(doctl compute load-balancer list | grep "k8s-monitoring" | cut -d' ' -f1)
if [ -n "${LB_ID}" ]; then
    doctl compute load-balancer delete "${LB_ID}" -f
fi

echo "- Destroying the node firewall"
FW_ID=$(doctl compute firewall list | grep "k8s-nodes" | cut -d' ' -f1)
if [ -n "${FW_ID}" ]; then
    doctl compute firewall delete "${FW_ID}" -f
fi

echo "- Destroying the master firewall"
FW_ID=$(doctl compute firewall list | grep "k8s-master" | cut -d' ' -f1)
if [ -n "${FW_ID}" ]; then
    doctl compute firewall delete "${FW_ID}" -f
fi

echo "- Destroy completed"
